In [1]:
import tensorflow as tf

In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

In [4]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

In [5]:
Y = tf.placeholder(tf.float32)

In [6]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [7]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [8]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [9]:
sess = tf.Session()

In [10]:
sess.run(tf.global_variables_initializer())

In [11]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  130410.336 
Prediction:
 [-164.38191 -203.47804 -197.22383 -217.03896 -154.8838 ]
10 Cost:  9.6420145 
Prediction:
 [155.05255 180.47935 181.085   194.93135 137.98297]
20 Cost:  8.404717 
Prediction:
 [156.00795 181.64865 182.2262  196.17558 138.87885]
30 Cost:  8.36143 
Prediction:
 [155.99977 181.65974 182.22623 196.1771  138.89127]
40 Cost:  8.318384 
Prediction:
 [155.98872 181.66733 182.22284 196.17488 138.90102]
50 Cost:  8.275564 
Prediction:
 [155.97768 181.67487 182.2194  196.17262 138.91069]
60 Cost:  8.233022 
Prediction:
 [155.96669 181.68239 182.21602 196.1704  138.92036]
70 Cost:  8.190707 
Prediction:
 [155.95573 181.68987 182.21262 196.16817 138.93002]
80 Cost:  8.148535 
Prediction:
 [155.94476 181.69734 182.20923 196.16595 138.93965]
90 Cost:  8.106648 
Prediction:
 [155.93387 181.70482 182.20586 196.16376 138.94925]
100 Cost:  8.064985 
Prediction:
 [155.92297 181.71225 182.2025  196.16156 138.95882]
110 Cost:  8.023526 
Prediction:
 [155.91211 181.71967 182

1000 Cost:  5.1032476 
Prediction:
 [155.05376 182.30608 181.93349 195.98756 139.72073]
1010 Cost:  5.077793 
Prediction:
 [155.04523 182.31187 181.93085 195.98587 139.72818]
1020 Cost:  5.05241 
Prediction:
 [155.03671 182.31769 181.92819 195.98419 139.73561]
1030 Cost:  5.027236 
Prediction:
 [155.02824 182.32347 181.92557 195.98253 139.74301]
1040 Cost:  5.0021143 
Prediction:
 [155.01978 182.32927 181.92294 195.98083 139.75041]
1050 Cost:  4.9772024 
Prediction:
 [155.01135 182.33502 181.92033 195.97919 139.75778]
1060 Cost:  4.9523892 
Prediction:
 [155.00294 182.34077 181.91772 195.97752 139.76514]
1070 Cost:  4.927703 
Prediction:
 [154.99454 182.3465  181.91512 195.97586 139.77246]
1080 Cost:  4.903145 
Prediction:
 [154.98616 182.35222 181.91252 195.97421 139.77977]
1090 Cost:  4.8787484 
Prediction:
 [154.97783 182.35793 181.90994 195.97258 139.78706]
1100 Cost:  4.8545055 
Prediction:
 [154.9695  182.36359 181.90738 195.97093 139.79433]
1110 Cost:  4.83035 
Prediction:
 [154

1950 Cost:  3.2037258 
Prediction:
 [154.3375  182.79495 181.71123 195.8481  140.34436]
1960 Cost:  3.188476 
Prediction:
 [154.33087 182.79944 181.70917 195.84682 140.35008]
1970 Cost:  3.173268 
Prediction:
 [154.32426 182.80394 181.7071  195.84554 140.3558 ]
1980 Cost:  3.1581812 
Prediction:
 [154.3177  182.80844 181.7051  195.84431 140.36151]
1990 Cost:  3.1431668 
Prediction:
 [154.31114 182.8129  181.70305 195.84305 140.3672 ]
2000 Cost:  3.1282165 
Prediction:
 [154.30461 182.81737 181.701   195.8418  140.37288]
