In [1]:
import tensorflow as tf

In [2]:
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], 
          [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

In [3]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [4]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [5]:
hypothesis = tf.matmul(X, W) + b

In [6]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [7]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [8]:
sess = tf.Session()

In [9]:
sess.run(tf.global_variables_initializer())

In [10]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  8955.515 
Prediction:
 [[60.358215]
 [88.28085 ]
 [78.17084 ]
 [91.17767 ]
 [66.7148  ]]
10 Cost:  19.43338 
Prediction:
 [[143.99588]
 [188.78072]
 [177.20888]
 [199.0247 ]
 [143.36673]]
20 Cost:  19.283672 
Prediction:
 [[144.2629 ]
 [189.07535]
 [177.51297]
 [199.35292]
 [143.58736]]
30 Cost:  19.216084 
Prediction:
 [[144.27763]
 [189.06682]
 [177.51834]
 [199.35585]
 [143.57674]]
40 Cost:  19.148874 
Prediction:
 [[144.29155]
 [189.05737]
 [177.52274]
 [199.35774]
 [143.56544]]
50 Cost:  19.082047 
Prediction:
 [[144.30547]
 [189.04802]
 [177.52719]
 [199.3597 ]
 [143.55421]]
60 Cost:  19.015457 
Prediction:
 [[144.3193 ]
 [189.0386 ]
 [177.53159]
 [199.36156]
 [143.54297]]
70 Cost:  18.94933 
Prediction:
 [[144.33315]
 [189.02928]
 [177.53603]
 [199.36351]
 [143.53183]]
80 Cost:  18.883389 
Prediction:
 [[144.34692]
 [189.01993]
 [177.54037]
 [199.36533]
 [143.52065]]
90 Cost:  18.817968 
Prediction:
 [[144.3607 ]
 [189.01068]
 [177.5448 ]
 [199.36728]
 [143.50958]]
100 

940 Cost:  14.314166 
Prediction:
 [[145.4083 ]
 [188.30338]
 [177.8797 ]
 [199.5014 ]
 [142.67265]]
950 Cost:  14.271782 
Prediction:
 [[145.41933]
 [188.29597]
 [177.88326]
 [199.50267]
 [142.664  ]]
960 Cost:  14.22977 
Prediction:
 [[145.43031]
 [188.2886 ]
 [177.8868 ]
 [199.504  ]
 [142.65536]]
970 Cost:  14.187906 
Prediction:
 [[145.44124]
 [188.28119]
 [177.89027]
 [199.50525]
 [142.64673]]
980 Cost:  14.1462345 
Prediction:
 [[145.45218]
 [188.27385]
 [177.89381]
 [199.50655]
 [142.63815]]
990 Cost:  14.104838 
Prediction:
 [[145.46306]
 [188.26651]
 [177.8973 ]
 [199.50781]
 [142.62958]]
1000 Cost:  14.063594 
Prediction:
 [[145.47394]
 [188.2592 ]
 [177.90082]
 [199.50911]
 [142.62103]]
1010 Cost:  14.022629 
Prediction:
 [[145.48476]
 [188.2519 ]
 [177.90428]
 [199.51036]
 [142.61252]]
1020 Cost:  13.981776 
Prediction:
 [[145.49554]
 [188.24458]
 [177.90773]
 [199.51158]
 [142.604  ]]
1030 Cost:  13.941182 
Prediction:
 [[145.50636]
 [188.23738]
 [177.91124]
 [199.51288]


1790 Cost:  11.375885 
Prediction:
 [[146.24962]
 [187.73738]
 [178.15115]
 [199.59175]
 [142.01932]]
1800 Cost:  11.3481 
Prediction:
 [[146.25847]
 [187.73143]
 [178.15402]
 [199.5926 ]
 [142.01256]]
1810 Cost:  11.320456 
Prediction:
 [[146.26727]
 [187.72548]
 [178.15688]
 [199.59343]
 [142.0058 ]]
1820 Cost:  11.29295 
Prediction:
 [[146.27611]
 [187.71962]
 [178.15976]
 [199.5943 ]
 [141.99913]]
1830 Cost:  11.265512 
Prediction:
 [[146.28488]
 [187.71371]
 [178.16261]
 [199.5951 ]
 [141.99243]]
1840 Cost:  11.238303 
Prediction:
 [[146.29361]
 [187.70781]
 [178.16542]
 [199.5959 ]
 [141.98573]]
1850 Cost:  11.211155 
Prediction:
 [[146.30237]
 [187.70197]
 [178.16826]
 [199.59673]
 [141.97908]]
1860 Cost:  11.184175 
Prediction:
 [[146.3111 ]
 [187.69612]
 [178.17111]
 [199.59758]
 [141.97247]]
1870 Cost:  11.157263 
Prediction:
 [[146.31978]
 [187.69028]
 [178.17392]
 [199.59834]
 [141.96584]]
1880 Cost:  11.130565 
Prediction:
 [[146.32841]
 [187.68443]
 [178.17673]
 [199.5991