In [1]:
import tensorflow as tf
import numpy as np

In [6]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [7]:
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [8]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [9]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [10]:
hypothesis = tf.matmul(X, W) + b

In [11]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [12]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [13]:
sess = tf.Session()

In [14]:
sess.run(tf.global_variables_initializer())

In [15]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  6670.29 
Prediction:
 [[74.801926]
 [95.69526 ]
 [91.31713 ]
 [98.66757 ]
 [75.187584]
 [55.13305 ]
 [71.244736]
 [48.940018]
 [89.940926]
 [82.2506  ]
 [71.17554 ]
 [72.510475]
 [95.188515]
 [80.67962 ]
 [72.36982 ]
 [95.85207 ]
 [79.590256]
 [83.555916]
 [89.982765]
 [79.7984  ]
 [84.55936 ]
 [88.71091 ]
 [80.35647 ]
 [77.374115]
 [98.581085]]
10 Cost:  26.847967 
Prediction:
 [[150.9109  ]
 [187.16406 ]
 [181.44598 ]
 [196.83138 ]
 [144.94017 ]
 [106.56823 ]
 [144.73572 ]
 [103.438644]
 [175.43152 ]
 [161.44977 ]
 [141.97131 ]
 [142.31598 ]
 [188.2971  ]
 [158.07008 ]
 [146.19826 ]
 [188.6784  ]
 [153.28418 ]
 [171.75815 ]
 [178.74854 ]
 [159.2246  ]
 [170.73578 ]
 [174.5279  ]
 [162.51761 ]
 [154.09402 ]
 [193.37589 ]]
20 Cost:  26.417236 
Prediction:
 [[151.43718 ]
 [187.7893  ]
 [182.06525 ]
 [197.51253 ]
 [145.40964 ]
 [106.923874]
 [145.2576  ]
 [103.84262 ]
 [176.02234 ]
 [162.01123 ]
 [142.46506 ]
 [142.8022  ]
 [188.92986 ]
 [158.58595 ]
 [146.72223 ]
 [189.31996 ]


310 Cost:  23.39884 
Prediction:
 [[151.4595  ]
 [187.60207 ]
 [181.9759  ]
 [197.60004 ]
 [145.06116 ]
 [106.927185]
 [145.65819 ]
 [104.61434 ]
 [176.0236  ]
 [162.40187 ]
 [142.5973  ]
 [142.90903 ]
 [188.64388 ]
 [158.06865 ]
 [147.11313 ]
 [189.32613 ]
 [152.98122 ]
 [173.0377  ]
 [179.0827  ]
 [159.58241 ]
 [171.71758 ]
 [175.14027 ]
 [163.41774 ]
 [154.18323 ]
 [193.77393 ]]
320 Cost:  23.303686 
Prediction:
 [[151.46033]
 [187.59563]
 [181.97289]
 [197.6028 ]
 [145.04941]
 [106.92697]
 [145.67133]
 [104.63977]
 [176.02322]
 [162.41422]
 [142.60153]
 [142.91223]
 [188.63441]
 [158.05164]
 [147.12589]
 [189.32603]
 [152.95534]
 [173.05902]
 [179.07387]
 [159.5764 ]
 [171.72975]
 [175.1406 ]
 [163.42827]
 [154.16942]
 [193.76555]]
330 Cost:  23.209116 
Prediction:
 [[151.46117]
 [187.58919]
 [181.9699 ]
 [197.60555]
 [145.03767]
 [106.92675]
 [145.68442]
 [104.66514]
 [176.02284]
 [162.4265 ]
 [142.60576]
 [142.91542]
 [188.62502]
 [158.03467]
 [147.1386 ]
 [189.32594]
 [152.92957

640 Cost:  20.535307 
Prediction:
 [[151.49223]
 [187.39499]
 [181.8834 ]
 [197.68767]
 [144.68651]
 [106.91292]
 [146.07324]
 [105.41787]
 [176.00314]
 [162.77742]
 [142.73016]
 [143.00357]
 [188.35033]
 [157.53773]
 [147.51416]
 [189.31856]
 [152.17   ]
 [173.71217]
 [178.8108 ]
 [159.40005]
 [172.10185]
 [175.14598]
 [163.75122]
 [153.75891]
 [193.5088 ]]
650 Cost:  20.456825 
Prediction:
 [[151.49338]
 [187.3889 ]
 [181.88081]
 [197.6902 ]
 [144.67555]
 [106.91227]
 [146.08525]
 [105.44109]
 [176.00227]
 [162.78783]
 [142.73396]
 [143.00609]
 [188.342  ]
 [157.52258]
 [147.52568]
 [189.31819]
 [152.14671]
 [173.7317 ]
 [178.80316]
 [159.395  ]
 [172.11295]
 [175.146  ]
 [163.7609 ]
 [153.74702]
 [193.50111]]
660 Cost:  20.378822 
Prediction:
 [[151.49454]
 [187.38281]
 [181.87823]
 [197.69275]
 [144.66463]
 [106.9116 ]
 [146.09721]
 [105.46425]
 [176.00139]
 [162.79817]
 [142.73776]
 [143.00858]
 [188.3337 ]
 [157.50749]
 [147.53717]
 [189.31781]
 [152.12352]
 [173.75117]
 [178.795

960 Cost:  18.235676 
Prediction:
 [[151.53302]
 [187.20517]
 [181.8061 ]
 [197.76637]
 [144.34792]
 [106.88679]
 [146.44157]
 [106.13055]
 [175.9694 ]
 [163.085  ]
 [142.84645]
 [143.0753 ]
 [188.0988 ]
 [157.07878]
 [147.86653]
 [189.30348]
 [151.46063]
 [174.31267]
 [178.58186]
 [159.25069]
 [172.44151]
 [175.1425 ]
 [164.04878]
 [153.40367]
 [193.27245]]
970 Cost:  18.170403 
Prediction:
 [[151.53441]
 [187.1994 ]
 [181.80386]
 [197.7687 ]
 [144.33769]
 [106.88581]
 [146.45256]
 [106.15182]
 [175.96817]
 [163.0938 ]
 [142.84987]
 [143.07726]
 [188.0914 ]
 [157.06523]
 [147.87698]
 [189.30289]
 [151.43959]
 [174.33063]
 [178.5752 ]
 [159.24638]
 [172.45163]
 [175.14227]
 [164.05768]
 [153.39337]
 [193.26535]]
980 Cost:  18.105478 
Prediction:
 [[151.53583]
 [187.19366]
 [181.80164]
 [197.77109]
 [144.32751]
 [106.88482]
 [146.46355]
 [106.17306]
 [175.96692]
 [163.10255]
 [142.85332]
 [143.07921]
 [188.08406]
 [157.05176]
 [147.88744]
 [189.30232]
 [151.41864]
 [174.34856]
 [178.568

1290 Cost:  16.266308 
Prediction:
 [[151.5821  ]
 [187.02052 ]
 [181.73743 ]
 [197.84152 ]
 [144.02272 ]
 [106.850006]
 [146.78934 ]
 [106.8031  ]
 [175.9236  ]
 [163.35234 ]
 [142.95476 ]
 [143.13213 ]
 [187.86937 ]
 [156.6564  ]
 [148.19609 ]
 [189.28175 ]
 [150.80035 ]
 [174.88145 ]
 [178.37677 ]
 [159.12082 ]
 [172.76097 ]
 [175.13155 ]
 [164.33119 ]
 [153.08742 ]
 [193.0483  ]]
1300 Cost:  16.212204 
Prediction:
 [[151.58368 ]
 [187.01509 ]
 [181.73549 ]
 [197.8437  ]
 [144.01324 ]
 [106.848755]
 [146.7994  ]
 [106.82254 ]
 [175.92206 ]
 [163.35973 ]
 [142.95787 ]
 [143.1336  ]
 [187.86284 ]
 [156.64433 ]
 [148.20558 ]
 [189.28102 ]
 [150.78139 ]
 [174.89792 ]
 [178.371   ]
 [159.11723 ]
 [172.77019 ]
 [175.1311  ]
 [164.33937 ]
 [153.07854 ]
 [193.0418  ]]
1310 Cost:  16.158371 
Prediction:
 [[151.58527]
 [187.00969]
 [181.73358]
 [197.8459 ]
 [144.00378]
 [106.84753]
 [146.80943]
 [106.84196]
 [175.92053]
 [163.3671 ]
 [142.96097]
 [143.13507]
 [187.85637]
 [156.63232]
 [148.21

1590 Cost:  14.768271 
Prediction:
 [[151.63121]
 [186.86217]
 [181.6834 ]
 [197.90492]
 [143.74701]
 [106.80994]
 [147.07967]
 [107.36428]
 [175.87454]
 [163.55772]
 [143.04405]
 [143.17113]
 [187.68407]
 [156.31224]
 [148.46881]
 [189.25783]
 [150.25644]
 [175.35765]
 [178.21411]
 [159.02104]
 [173.02672]
 [175.11644]
 [164.56807]
 [152.83815]
 [192.86043]]
1600 Cost:  14.722553 
Prediction:
 [[151.6329  ]
 [186.85703 ]
 [181.68173 ]
 [197.90697 ]
 [143.73813 ]
 [106.808525]
 [147.08893 ]
 [107.38222 ]
 [175.8728  ]
 [163.564   ]
 [143.04689 ]
 [143.17223 ]
 [187.67824 ]
 [156.30136 ]
 [148.4775  ]
 [189.25696 ]
 [150.23917 ]
 [175.3729  ]
 [178.20905 ]
 [159.01797 ]
 [173.03519 ]
 [175.11586 ]
 [164.57565 ]
 [152.83041 ]
 [192.8544  ]]
1610 Cost:  14.677082 
Prediction:
 [[151.63461]
 [186.85193]
 [181.68008]
 [197.90903]
 [143.7293 ]
 [106.8071 ]
 [147.0982 ]
 [107.4001 ]
 [175.8711 ]
 [163.57027]
 [143.04973]
 [143.17334]
 [187.67244]
 [156.29056]
 [148.48616]
 [189.25613]
 [150.2

1910 Cost:  13.424217 
Prediction:
 [[151.68692 ]
 [186.70294 ]
 [181.63348 ]
 [197.96777 ]
 [143.47258 ]
 [106.762054]
 [147.36456 ]
 [107.91473 ]
 [175.81653 ]
 [163.74292 ]
 [143.13066 ]
 [143.20168 ]
 [187.50793 ]
 [155.9823  ]
 [148.73422 ]
 [189.22906 ]
 [149.72942 ]
 [175.82623 ]
 [178.06238 ]
 [158.93105 ]
 [173.28665 ]
 [175.09619 ]
 [164.80156 ]
 [152.60715 ]
 [192.67538 ]]
1920 Cost:  13.385938 
Prediction:
 [[151.68869]
 [186.69814]
 [181.63203]
 [197.96967]
 [143.46431]
 [106.76049]
 [147.37308]
 [107.93118]
 [175.81464]
 [163.74818]
 [143.13322]
 [143.20247]
 [187.50276]
 [155.97256]
 [148.74213]
 [189.2281 ]
 [149.71378]
 [175.84026]
 [178.05797]
 [158.92848]
 [173.2944 ]
 [175.0955 ]
 [164.80856]
 [152.60046]
 [192.66985]]
1930 Cost:  13.347865 
Prediction:
 [[151.69048]
 [186.69331]
 [181.63058]
 [197.97154]
 [143.45607]
 [106.75892]
 [147.38158]
 [107.94758]
 [175.81273]
 [163.75343]
 [143.13579]
 [143.20323]
 [187.4976 ]
 [155.96284]
 [148.74998]
 [189.22716]
 [149.6